### ISSUE TITLE
Cannot use USE

### ISSUE THREAD

**Issue by jdiamond** [cloudspannerecosystem/cassandra-to-spanner-proxy#21]
The proxy does not seem to use keyspaces set with `USE`.

One of our applications is using Spring Data for Cassandra and it is using `USE` before executing any queries. All subsequent queries don't reference the keyspace and are failing. Our other applications don't use Spring Data so this hasn't been a problem until now.

I can reproduce it with cqlsh and think it might be an issue with the proxy.

Create a table in Spanner or use an existing one. It doesn't need any data to see the error.

```sql
create table data (
  id string(max)
) primary key (id);
```

Add the metadata if you need it:

```sql
INSERT INTO TableConfigurations (KeySpaceName, TableName, ColumnName, ColumnType, IsPrimaryKey, PK_Precedence) VALUES ('test', 'data', 'id', 'text', true, 0);
```

Try to query from this table without the keyspace in cqlsh:

```cql
SELECT * FROM data;
```

Of course that fails with this error message:

```
InvalidRequest: Error from server: code=2200 [Invalid query] message="could not find table or keyspace name"
```

But it works when you include the keyspace:

```cql
SELECT * FROM test.data;
```

Try to use the `USE` keyword then query without the keyspace:

```cql
USE test;
SELECT * FROM data;
```

And the same error as up above appears.

**Comment by mayurkale22** [comment]
Thank you for reporting this issue, @jdiamond. At this time, the USE keyword is not supported with proxy. Please let us know how this impacts your workflow. Do you have a workaround, or is this a significant obstacle for your applications? This information will assist us in prioritizing this task.

**Comment by jdiamond** [comment]
I have not found a way to control this behavior in Spring Data for Cassandra so we don't currently have a workaround.

**Comment by mayurkale22** [comment]
This should be fixed in https://github.com/cloudspannerecosystem/cassandra-to-spanner-proxy/pull/22

**Comment by mayurkale22** [comment]
Hi @jdiamond, I have submitted the fix (#22), could you pls use the main branch and verify the fix?

**Comment by jdiamond** [comment]
Hi @mayurkale22, tested it today and no problems so far. Still need to run our regression tests, but my manual tests are working. Thanks so much for the quick update!

**Comment by mayurkale22** [comment]
Thanks for the confirmation, closing the bug now. Feel free to reopen if you find any issues
